image: "registry.gitlab.com/l4r0x/sbv-gd"

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version
    - cargo test -- --nocapture
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - $CARGO_HOME
      - target/
      - Cargo.toml


# Use godot headless to run the ui tests
test:godot:
  script:
    - ./bin/headless/Godot_v3.2.3-stable_linux_headless.64 -s ui/test/TestUtil.gd



deploy:linux:
  script:
    - cargo build --release
    - mkdir export/x11
    - ./bin/headless/Godot_v3.2.3-stable_linux_headless.64 --export "Linux/X11 - Tiny" export/x11/sbv-gd.x86_64
  when: manual
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: [export/x11/*]
    expire_in: 1 week

deploy:windows:
  script:
    - cargo build --target=x86_64-pc-windows-gnu --release
    - mkdir export/windows
    - ./bin/headless/Godot_v3.2.3-stable_linux_headless.64 --export "Windows - Tiny" export/windows/sbv-gd.x86_64
  when: manual
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: [export/windows/*]
    expire_in: 1 week
