image: "rust"

before_script:
  - apt-get update
  - apt-get install --assume-yes libclang-9-dev

# Use cargo to test the project
test:cargo:
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose

# Use godot headless to run the ui tests
test:godot:
  script:
    - ./bin/headless/Godot_v3.2.3-stable_linux_headless.64 -s ui/test/TestUtil.gd
