image: "registry.gitlab.com/wrenger/sbv-gd"

# Global config
variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo_home"

# Use cargo to test the project
test:cargo:
  stage: test
  script:
    - rustc --version && cargo --version
    - cargo test -- --nocapture
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - $CARGO_HOME
      - target/
      - Cargo.lock

# Use godot headless to run the ui tests
test:godot:
  stage: test
  script:
    - ./bin/headless/Godot_v3.3-stable_linux_headless.64 -s test/TestUtil.gd
    - ./bin/headless/Godot_v3.3-stable_linux_headless.64 -s test/TestUserProvider.gd


# Deployment

deploy:linux:
  stage: deploy
  script:
    - cargo build --release
    - mkdir export/x11
    - ./bin/headless/Godot_v3.3-stable_linux_headless.64 --export x11 export/x11/sbv-gd.x86_64
  when: manual
  artifacts:
    name: "sbv-x11-$CI_COMMIT_REF_NAME"
    paths: [export/x11/*]
    expire_in: 1 week

deploy:windows:
  stage: deploy
  script:
    - cargo build --target=x86_64-pc-windows-gnu --release
    - mkdir export/win
    - ./bin/headless/Godot_v3.3-stable_linux_headless.64 --export win export/win/sbv-gd.exe
  when: manual
  artifacts:
    name: "sbv-win-$CI_COMMIT_REF_NAME"
    paths: [export/win/*]
    expire_in: 1 week
