name: Dist

on:
  release:
    types: [ published ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-svelte:
    name: Build Svelte
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Svelte
      run: npm install
      working-directory: lib-view
    - name: Build Svelte
      run: npm run build
      working-directory: lib-view
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: lib-view
        path: lib-view/build

  build-rust:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          exe: schiller-lib
        - os: windows-latest
          exe: schiller-lib.exe

    steps:
    - name: Build
      run: cargo build --release
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.exe }}
        path: target/release/${{ matrix.exe }}

  package:
    name: Package ${{ matrix.platform }}
    runs-on: ubuntu-latest
    needs: [build-svelte, build-rust]

    strategy:
      matrix:
        include:
        - platform: linux
          exe: schiller-lib
        - platform: window
          exe: schiller-lib.exe

    steps:
    - uses: actions/checkout@v2
    - name: Setup Output
      run: mkdir -p build
    - name: Download lib-view
      uses: actions/download-artifact@v2
      with:
        name: lib-view
        path: build/lib-view
    - name: Download server
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.exe }}
        path: build/${{ matrix.exe }}
    - name: Package
      run: zip -r schiller-lib-${{ matrix.platform }}.zip build
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: schiller-lib-${{ matrix.platform }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
